### ISSUE TITLE
Error downloading airport data

### ISSUE THREAD

**Issue by marksteelefl** [RISCfuture/SF50-TOLD#1]
After installing on iPhone, when attempting to download initial airport data, receive the attached error after 30 seconds or so. Tried this on multiple devices. Devices are plugged in on WiFi. 
IOS 15.6.1

![9EFA3040-0A5D-46A4-8302-9C54502F8A52](https://user-images.githubusercontent.com/24435406/190930731-5befc9a1-c738-47c5-8c91-940e3f8542b8.jpeg)

**Comment by RISCfuture** [comment]
Will be fixed in the upcoming release.

**Comment by marksteelefl** [comment]
Any idea of timeframe for updated release?

thanks.

**Comment by RISCfuture** [comment]
It's been released for a few days now. Check your App Store updates.

**Comment by marksteelefl** [comment]
Appreciate the quick update. A friend of mine purchased his SF50 for about 6 months ago and your app was recommended to him by a fellow SF50 pilot. He did get the update and has been working with it.
